<a href="https://colab.research.google.com/github/yannfaiq/link-untuk-pycharm/blob/main/Pertemuan_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
alist = ["jhon", 33, "Toronto", True]
print(alist)

['jhon', 33, 'Toronto', True]


In [ ]:
bin_colors=['Red', 'Green', 'Blue', 'Yellow']
bin_colors [1]

'Green'

In [ ]:
bin_colors=['Red', 'Green', 'Blue', 'Yellow']
bin_colors [0:2]

['Red', 'Green']

In [3]:
from datetime import date
tgl_v1 = date.today()
print(tgl_v1)

import datetime as vDate
hari = vDate.date.today()
tanggal = vDate.date.today()
print(hari)
print(tanggal)

mahasiswa = ["ziyan", "2024071014", "informatika", "DAA", f"{tanggal.day}-{tanggal.month}-{tanggal.year}", "UPJ"]
print(mahasiswa)


2025-09-15
2025-09-15
2025-09-15
['ziyan', '2024071014', 'informatika', 'DAA', '15-9-2025', 'UPJ']


In [8]:
print ("NIM dan Prodi", mahasiswa[1:2], mahasiswa[2:3])

NIM dan Prodi ['2024071014'] ['informatika']


In [4]:
print ("Nama Kampus", mahasiswa[5:6])

Nama Kampus ['UPJ']


In [6]:
print ("Tanggal dan Prodi", mahasiswa[4:5], mahasiswa[2:3])

Tanggal dan Prodi ['15-9-2025'] ['informatika']


In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
for aColor in bin_colors:
    print(aColor + 'square')

Redsquare
Greensquare
Bluesquare
Yellowsquare


In [ ]:
for aMhs in mahasiswa:
  print(aMhs + ' UPJ')

ziyan UPJ
2024071014 UPJ
informatika UPJ
DAA UPJ
15-9-2025 UPJ
UPJ UPJ


In [ ]:
UPJ = ['Universitas', 'Pembangunan', 'Jaya']
for aUPJ in UPJ:
  print(aUPJ + ' UPJ')

Universitas UPJ
Pembangunan UPJ
Jaya UPJ


In [ ]:
nested_tuple = (100, (200, 400, 600), 300, (400, 800))

print(nested_tuple)


(100, (200, 400, 600), 300, (400, 800))


In [ ]:
data_mahasiswa = {
    "Nama": "Ziyan Faiq Rifai",
    "NIM": "2024071014",
    "Prodi": "Informatika",
    "Universitas": "UPJ"
}
print(data_mahasiswa)

{'Nama': 'Ziyan Faiq Rifai', 'NIM': '2024071014', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [ ]:
# Buat dictionary sesuai tabel
data_mahasiswa = {
    "Nama": "Ziyan Faiq Rifai",
    "NIM": "2024071014",
    "Prodi": "Informatika",
    "Universitas": "UPJ"
}

# Tampilkan dictionary
for k, v in data_mahasiswa.items():
    print(k, ":", v)



Nama : Ziyan Faiq Rifai
NIM : 2024071014
Prodi : Informatika
Universitas : UPJ


In [ ]:
df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [ ]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [ ]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [ ]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]])
df

0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True

In [ ]:
import pandas as pd

df = pd.DataFrame([
    ['1', 'Informatika', 50, 30, 20],
    ['2', 'Sistem Informasi', 55, 30, 25],
    ['3', 'Teknik Sipil', 40, 30, 10]
],
columns=['No', 'Prodi', 'Mahasiswa', 'Laki-laki', 'Perempuan'])

print(df)


  No             Prodi  Mahasiswa  Laki-laki  Perempuan
0  1       Informatika         50         30         20
1  2  Sistem Informasi         55         30         25
2  3      Teknik Sipil         40         30         10


In [ ]:
import numpy as np

# Buat matriks
myMatrix = np.array([[100, 200, 300],
                     [700, 600, 500],
                     [900, 1000, 800]])

print("Matriks asli:")
print(myMatrix)

# Transpose matriks
transposed = myMatrix.T  # atau np.transpose(myMatrix)

print("\nMatriks setelah transpose:")
print(transposed)


Matriks asli:
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]

Matriks setelah transpose:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [ ]:
q = Queue()
q.enqueue(1)
q.enqueue(2)
q.enqueue(3)
print(q.size())     # 3
print(q.dequeue())  # 1
print(q.isEmpty())  # False

3
1
False


In [ ]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0, item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)
